CREATE DATABASE vendas2026

USE vendas2026

CREATE TABLE marca(
	idMarca int PRIMARY KEY, -- este comando torna o campo como PK
	nome varchar(80),
	situacao char(1)
)

-- CADASTRAR MARCAS UMA DE CADA VEZ:
INSERT INTO marca
VALUES (1, 'COCA-COLA', 'A')

INSERT INTO marca
VALUES (2, 'PEPSI', 'A')

-- CADASTRAR VARIAS MARCAS DE UMA VEZ:
INSERT INTO marca
VALUES 
	(3, 'ANTARTICA', 'I'),
	(4, 'FORS', 'A'),
	(5, 'SKOL', 'I')

-- CRIAR A TABELA PRODUTO COM PK MAS AINDA SEM FK
CREATE TABLE produto(
	idPro int PRIMARY KEY,
	nome varchar(100),
	preco money,
	car varchar(40)
)

-- TESTANDO PROPRIEDADE DE 'NÃO NULO' DA PK:
INSERT INTO marca (nome)
VALUES ('TESTE', 'A')

-- TESTANDO PROPRIEDADE DE 'VALOR UNICO' DA PK:
INSERT INTO marca
VALUES (1, 'NOVO TESTE', 'A')

-- APAGAR TABELA:
DROP TABLE produto

-- CRIAR A TABELA PRODUTO COM PK COM NUMERAÇÃO AUTOMÁTICA E COM FK PARA MARCA
CREATE TABLE produto(
	idPro int PRIMARY KEY IDENTITY(1,1),
	nome varchar(100),
	preco money,
	cor varchar(40),
	idMarca int FOREIGN KEY REFERENCES marca(idMarca)
)

INSERT INTO produto(nome, preco)
VALUES ('COCA LATA 340 mL', 8.94)

UPDATE produto SET idMarca = 3
WHERE idPro = 1

-- RETORNO DA TABELA PRODUTO
SELECT * FROM produto

-- RETORNO DA TABELA MARCA
SELECT * FROM marca

-- CRIAR NOVA TABELA PARA CADASTRO DE FORNECEDORES
CREATE TABLE fornecedor(
	idFor int PRIMARY KEY IDENTITY(1,1),
	razaoSocial varchar(50),
	cnpj varchar(20)
)

-- RETORNO DA TABELA FORNECEDOR
SELECT * FROM fornecedor

-- ALTERAR A ESTRUTURA DA TABELA PRODUTO PARA UMA NOVA FK LIGANDO AO FORNECEDOR:
ALTER TABLE produto
	ADD idFor INT FOREIGN KEY REFERENCES fornecedor(idFor)

-- EXERCICIOS DE FIXAÇÃO:
1. CADASTRE 3 PRODUTOS INFORMANDO SÓ O NOME E O PREÇO
2. CADASTRE 4 FORNECEDORES PREENCHENDO TODOS OS CAMPOS
3. ALTERE O NOME DA MARCA SKOL PARA 'LEVISSIMA'
4. CADASTRE 2 PRODUTOS INFORMANDO TODOS OS CAMPOS DA TABELA
5. ATUALIZE O CNPJ DO FORNECEDOR CUJO idFor é 3 PARA TER VALOR '123456789'
6. ATUALIZE TODOS OS PRODUTOS QUE NÃO TEM MARCA PARA TEREM ALGUM idMarca
7. EXCLUA O PRODUTO DE CÓDIGO = 2
8. EXCLUA A MARCA DE CÓDIGO = 4
9. ACRESCENTE EM 10% A MAIS NO PREÇO DOS PRODUTOS QUE TEM PREÇO MAIOR QUE ZERO
10. EXCLUA (APAGUE) A TABELA FORNECEDOR

INSERT INTO produto (nome, preco)
VALUES
	('FANTA', 3.9),
	('SPRITE', 4),
	('SODA', 5)

INSERT INTO fornecedor
VALUES
	('HEL', '4214215430001-42'),
	('KAI', '4214215430001-46'),
	('LET', '4214215430001-43'),
	('ART', '4214215430001-41')